# -*- coding: UTF-8 -*-
from icv.detector import MbDetector

if __name__ == '__main__':
    classes = [
        # "__background",
        "person",
        "bicycle",
        "car",
        "motorcycle",
        "airplane",
        "bus",
        "train",
        "truck",
        "boat",
        "traffic light",
        "fire hydrant",
        "stop sign",
        "parking meter",
        "bench",
        "bird",
        "cat",
        "dog",
        "horse",
        "sheep",
        "cow",
        "elephant",
        "bear",
        "zebra",
        "giraffe",
        "backpack",
        "umbrella",
        "handbag",
        "tie",
        "suitcase",
        "frisbee",
        "skis",
        "snowboard",
        "sports ball",
        "kite",
        "baseball bat",
        "baseball glove",
        "skateboard",
        "surfboard",
        "tennis racket",
        "bottle",
        "wine glass",
        "cup",
        "fork",
        "knife",
        "spoon",
        "bowl",
        "banana",
        "apple",
        "sandwich",
        "orange",
        "broccoli",
        "carrot",
        "hot dog",
        "pizza",
        "donut",
        "cake",
        "chair",
        "couch",
        "potted plant",
        "bed",
        "dining table",
        "toilet",
        "tv",
        "laptop",
        "mouse",
        "remote",
        "keyboard",
        "cell phone",
        "microwave",
        "oven",
        "toaster",
        "sink",
        "refrigerator",
        "book",
        "clock",
        "vase",
        "scissors",
        "teddy bear",
        "hair drier",
        "toothbrush",
    ]
    detector = MbDetector(
        model_path="/Users/rensike/Resources/models/pytorch/e2e_faster_rcnn_R_50_FPN_1x.pth",
        config_file="/Users/rensike/Workspace/my_study/study_maskrcnn_benchmark/configs/e2e_faster_rcnn_R_50_FPN_1x_caffe2.yaml",
        categories=classes,
        iou_thr=0.9
    )

    # detector.inference("/Users/rensike/Files/data/images/street.jpg",is_show=True)

    detector.start_server(port=9528,secret="keke",upload_dir="./uploads")

